### ISSUE TITLE
Default Volume Can't be anything but 1

### ISSUE THREAD

**Issue by TerryJColes** [G-a-v-r-o-c-h-e/PIpod-Nano#2]
I may have missed something in the script, but I am unable to define a different default volume for the player to user at startup.  Line 9 of autoplay.sh says: `mpc volume 1`, so I would expect the volume to be at minimum when the player starts.  However, I want to use this software to play sound effects at our local Model Town and want the startup volume to be about 20%, so I modified that line to read `mpc volume 19`.   Unfortunately that didn't work.  I then moved Line 9 further down the script to Line 37 (in other words after the playback has commenced); still no joy.

I can modify the volume after startup by sending the required level from the command line, but I don't seem to be able to do it as part of the boot script.  I'm assuming that the initial value is being overwritten somewhere, but I can't see where.

Have I missed something obvious?

**Comment by PetitPrinc3** [comment]
Hi !

So you're not missing anything from where I stand. 
Make sure you edit this file with root privileges, maybe that's the issue (?). 
What you can try to do is remove the "mpc volume 1" line and see what it does. 
And btw, to have a 20% volume, the command is "mpc volume 20" 😉
Otherwise I literally have no idea why it behaves this way...
Let me know !

**Comment by TerryJColes** [comment]
> Make sure you edit this file with root privileges, maybe that's the issue (?).

I'll try it, but the modified line is still there when I re-open the file so I somehow doubt that is the problem.

> What you can try to do is remove the "mpc volume 1" line and see what it does.

OK.  I'm testing the sound effects at the moment, so I'll have another look later.

> And btw, to have a 20% volume, the command is "mpc volume 20" 

:-)  I did say approximately 20%.

> Otherwise I literally have no idea why it behaves this way...

OK.  I'll keep digging.

> Let me know !

I will.

**Comment by TerryJColes** [comment]
I've found a kludge :-)

Reasoning that something was happening to the mpc volume after autoplay.sh ran, I looked around for other places where the volume is changed and soon found buttons.py.  Clearly if `mpc volume +5` is working in there, then I might be able to define the starting volume there instead.  I added this code above the while loop:
```
#Set startup Volume
#Wait for PIpod-nano startup script to finish
time.sleep(20)
os.system("mpc volume 19")
```

I determined the delay empirically.  Without it the volume change throws an error (no connection to mpd) and if it's too short it fails too.  It takes about 20 seconds for the startup code to run and for the screen to start to display the first track, so this is probably about right.  If there are any more problems, I can afford to increase it a bit.

There is probably a better way, but I couldn't find it.

**Comment by gyuchulm** [comment]
you should find the autoplay.sh file in the place /usr/share/PIpodScrips in there has an option of the volume of mpc writes as 1 you should change the parameter on that, then It works with start with high volume
